#include "defs.h"

void printBit(uint64_t pbit, uint64_t size) {
	char pStr[255]; char cur;
	uint64_t i, c;
	for( c=0, i=size-1; i>0; i--, c++ ) {
		cur = (pbit & (uint64_t)1<<i) ? '1' : '0';
		pStr[c] = cur;
	} pStr[c] = (pbit & (uint64_t)1<<i) ? '1' : '0';
	pStr[++c] = '\0';
	LOG("%s", pStr);
}

char *ata_cmd_names[TOTCMDS] = {
	"ATA_IDENTIFY_DEVICE",
	"ATA_READ_NATIVE_MAX_ADDRESS_EXT",
	"ATA_READ_NATIVE_MAX_ADDRESS",
	"ATA_SET_FEATURES",
	"ATA_DEVICE_RESET",
	"ATA_FLUSH_CACHE_EXT",
	"ATA_FLUSH_CACHE",
	"ATA_PACKET",
	"ATA_IDENTIFY_PACKET_DEVICE",
	"ATA_SET_MULTIPLE_MODE",
	"ATA_STANDBY_IMMEDIATE",
	"ATA_CHECK_POWER_MODE",
	"ATA_INITIALIZE_DEVICE_PARAMETERS",
	"ATA_IDLE_IMMEDIATE",
	"ATA_RECALIBRATE",
	"ATA_NOP",
	"ATA_READ_VERIFY_SECTORS_EXT",
	"ATA_READ_VERIFY_SECTORS",
	"ATA_READ_VERIFY_SECTORS_WITHOUT_RETRIES",
	"ATA_SLEEP",
	"ATA_READ_DMA_EXT",
	"ATA_READ_DMA",
	"ATA_WRITE_DMA_EXT",
	"ATA_WRITE_DMA",
	"ATA_READ_FPDMA_QUEUED",
	"ATA_WRITE_FPDMA_QUEUED",
	"ATA_READ_LOG_EXT",
	"ATA_DATA_SET_MANAGEMENT",
////	"ATA_SECURITY_FREEZE_LOCK",
////	"ATA_SMART",
////	"ATA_NV_CACHE",
////	"ATA_IDLE",
////	"ATA_TRUSTED_RECEIVE_DMA",
};

uint8_t ata_cmd_vals[TOTCMDS] = {
	0xec, // ATA_IDENTIFY_DEVICE
	0x27, // ATA_READ_NATIVE_MAX_ADDRESS_EXT
	0xf8, // ATA_READ_NATIVE_MAX_ADDRESS
	0xef, // ATA_SET_FEATURES
	0x08, // ATA_DEVICE_RESET
	0xea, // ATA_FLUSH_CACHE_EXT
	0xe7, // ATA_FLUSH_CACHE
	0xa0, // ATA_PACKET
	0xa1, // ATA_IDENTIFY_PACKET_DEVICE
	0xc6, // ATA_SET_MULTIPLE_MODE
	0xe0, // ATA_STANDBY_IMMEDIATE
	0xe5, // ATA_CHECK_POWER_MODE
	0x91, // ATA_INITIALIZE_DEVICE_PARAMETERS
	0xe1, // ATA_IDLE_IMMEDIATE
	0x10, // ATA_RECALIBRATE
	0x00, // ATA_NOP
	0x42, // ATA_READ_VERIFY_SECTORS_EXT
	0x40, // ATA_READ_VERIFY_SECTORS
	0x41, // ATA_READ_VERIFY_SECTORS_WITHOUT_RETRIES
	0xe6, // ATA_SLEEP
	0x25, // ATA_READ_DMA_EXT
	0xc8, // ATA_READ_DMA
	0x35, // ATA_WRITE_DMA_EXT
	0xca, // ATA_WRITE_DMA
	0x60, // ATA_READ_FPDMA_QUEUED
	0x61, // ATA_WRITE_FPDMA_QUEUED
	0x2f, // ATA_READ_LOG_EXT
	0x06, // ATA_DATA_SET_MANAGEMENT
};